restApi/modules/__init__.py
from flask import Flask
from flask.helpers import url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, logout_user, current_user
from functools import wraps
from werkzeug.utils import redirect

app = Flask(__name__)
app.config.from_object('configuration.DevelopmentConfig')
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.login_view = "fauth.login"
login_manager.init_app(app)

def rol_admin_need(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        if current_user.rol.value != 6:
            logout_user()
            return redirect(url_for('fauth.login'))
        
        return f(*args, **kwds)
    
    return wrapper

from modules.product.product import product
from modules.product.category import category
from modules.auth.views import auth
from modules.fauth.views import fauth

# Rest
from modules.rest_api.product_api import product_view
from modules.rest_api.category_api import category_view

app.register_blueprint(product)
app.register_blueprint(category)
# app.register_blueprint(auth)
app.register_blueprint(fauth)
db.create_all()

# SQLite
# sqlite:///database.db

# Postgres
# postgresql+psycopg2://user:password@ip:port/db_name

# MSSQL
# mssql+pyodbc://user:password@dsn_name

# Oracle
# oracle+cx_oracle://user:password@ip:port/db_name

@app.template_filter('mydouble')
def mydouble_filter(n:int):
    return n * 2

restApi/modules/fauth/views.py
from flask import Blueprint, session, render_template, request, redirect, flash, get_flashed_messages
from werkzeug.exceptions import abort
from flask.helpers import url_for
from modules import db, login_manager
from modules.auth.model.user import User, LoginForm, RegisterForm
from flask_login import login_user, logout_user, current_user, login_required

fauth = Blueprint('fauth', __name__)

@login_manager.user_loader
def load_user(user_id):
   return User.query.get(user_id)


@fauth.route('/register', methods=['GET', 'POST'])
def register():
   form = RegisterForm(meta={'csrf': False})

   if form.validate_on_submit():
      if User.query.filter_by(username = form.username.data).first():
         flash("Usuario no válido.", 'danger')
      else:
         u = User(form.username.data, form.password.data)
         db.session.add(u)
         db.session.commit()
         flash("Usuario creado exitosamente.")
         return redirect(url_for('auth.register'))
   
   if form.errors:
      flash(form.errors, 'danger')

   return render_template('auth/register.html', form=form)  

@fauth.route('/login', methods=['GET', 'POST'])
def login():
   if current_user.is_authenticated:
      flash("Usuario ya autenticado.")
      return redirect(url_for('product.index'))

   form = LoginForm(meta={'csrf': False})

   if form.validate_on_submit():
      user = User.query.filter_by(username = form.username.data).first()

      if user and user.check_password(form.password.data):
         login_user(user)
         flash("Bienvenido, " + user.username)
         next = request.form['next']

         #if not is_safe_url(next):
            #return abort(400)

         return redirect(next or url_for('product.index'))
      else:
         flash("Credenciales incorrectas.")
   
   if form.errors:
      flash(form.errors, 'danger')

   return render_template('auth/login.html', form=form)

@fauth.route('/logout')
def logout():
   logout_user()
   return redirect(url_for('fauth.login'))

@fauth.route('/protegido')
@login_required
def protegido():
   return "Vista protegida"

restApi/modules/product/__init__.py
# Sin contenido, aunque necesario para levantar la aplicacion

restApi/modules/templates/category/_form.html
<div class="mb-3">
    {{ form.name.label }} 
    {{ form.name(class="form-control") }}
</div>

restApi/modules/templates/category/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('category.create') }}" method="POST">
        {% include 'category/_form.html' %}
        <input class="btn btn-success" type="submit" value="Guardar">
    </form>
{% endblock %}

restApi/modules/templates/category/filter.html
<h3>{{ product['name'] }}</h3>
<p>{{ product['category'] }}</p>
<p>{{ product['price'] }}</p>

<p>Filtro default: {{ product['price'] | default('Sin precio', True) }}</p>
<p>Filtro safe: {{ "<h1>Hola, mundo</h1>" | safe }}</p>
<p>Filtro truncate: {{ "Esto es la descripción de un producto bastante bonito" | truncate(20) }}</p>
<p>Filtro count: {{ "Esto es la descripción de un producto bastante bonito" | count }}</p>
<p>Filtro float: {{ 70 | float }}</p>
<p>Filtro int: {{ "70.8" | int }}</p>
<p>Filtro round: {{ 3.1415926535 | round(3) }}</p>
<p>Filtro join: {{ ["iPhone", "iPad"] | join(", ") }}</p>
<p>Filtro length: {{ ["iPhone", "iPad"] | length }}</p>
<p>Filtro tojson: {{ {'offer': False, 'price': 50.5, 'k': 45} | tojson }}</p>
<p>Filtro global personalizado: {{ 50 | mydouble }}</p>
<p>Filtro local personalizado: {{ product | iva }}</p>

restApi/modules/templates/category/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}
    <a href="{{ url_for('category.create') }}" class="btn btn-primary mt-2 mb-2"><i class="fa fa-plus"></i> Crear</a>
    <br>
    <div class="list-category">
        {% for category in categories.items %}
            <div class="p-4 mb-4 rounded-3 {{ loop.cycle('odd', 'even') }}">
                <h3>
                    <a href="{{ url_for('category.show', id=category['id']) }}">{{ category['name'] }}</a>
                </h3>
                <a class="btn btn-warning btn-sm" href="{{ url_for('category.update', id=category['id']) }}"><i class="far fa-edit" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar"></i></a>
                <button type="button" data-bs-toggle="modal" data-bs-target="#deleteModal" data-bs-name="{{ category['name'] }}" data-bs-id="{{ category['id'] }}" class="btn btn-danger btn-sm"><i class="far fa-trash-alt" data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar"></i></button>
            </div>
        {% endfor %}
    </div>

    {{ m_pagination(categories) }}

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Eliminar: <span></span></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Estás seguro de querer borrar este registro?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <a href="#" id="deleteProduct" class="btn btn-danger">Eliminar</a>
            </div>
          </div>
        </div>
    </div>

    <script>
        window.onload = function() {
            var deleteModal = document.getElementById('deleteModal')
            deleteModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget
            var id = button.getAttribute('data-bs-id')
            var name = button.getAttribute('data-bs-name')
            var modalTitle = deleteModal.querySelector('.modal-title span')
            var modalBodyInput = deleteModal.querySelector('.modal-body input')
            modalTitle.textContent = name
            $("#deleteProduct").attr("href", "/delete-category/" + id)
            })
        }
    </script>    
{% endblock %}

restApi/modules/templates/category/show.html
{% extends 'layout/base.html' %}

{% block container %}
    <h3>{{ product['name'] }}</h3>

    <p>{{ product['category'] }}</p>
    <p>$ {{ product['price'] }}</p>

    {% if product['price'] >= 1000 %}
        <p>Precio regular</p>
    {% else %}
        <p>Precio oferta</p>
    {% endif %}
{% endblock %}

restApi/modules/templates/category/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('category.update', id=category.id) }}" method="POST">
        {% include 'category/_form.html' %}
        <input class="btn btn-success" type="submit" value="Actualizar">
    </form>
{% endblock %}

restApi/modules/templates/fragment/_alert.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

restApi/modules/templates/fragment/_footer.html
<footer class="bg-light text-center text-lg-start">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2021 Copyright:
      <a class="text-dark" href="#">A. Gálvez</a>
    </div>
</footer>

restApi/modules/templates/fragment/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Flask</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if current_user.username %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('product.index') }}">Inicio</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              CRUD
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{ url_for('product.index') }}">Productos</a></li>
              <li><a class="dropdown-item" href="{{ url_for('category.index') }}">Categorías</a></li>
            </ul>
          </li>
        {% endif %}
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        {% if current_user.username %}
          
        {% else %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('fauth.login') }}">Iniciar sesión</a>
          </li>
        {% endif %}

        {% if current_user.username %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ current_user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Perfil</a></li>
              <li><a class="dropdown-item" href="{{ url_for('fauth.logout') }}">Cerrar sesión</a></li>
            </ul>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

restApi/modules/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='product/css/style.custom.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='global/css/style.custom.css') }}">
    <title>CRUD</title>
</head>
<body>
    {% include 'fragment/_nav.html'%}

    <div class="container">
        {% include 'fragment/_alert.html'%}
        {% block container %}
        
        {% endblock %}
    </div>

    {% include 'fragment/_footer.html'%}
    <script src="{{ url_for('static', filename='global/js/jquery-3.6.0.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='global/js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='product/js/main.js') }}"></script>
</body>
</html>

restApi/modules/templates/macro/_pagination.html
{% macro m_pagination(pagination) %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if pagination.has_prev %}
                <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=pagination.prev_num) }}">&laquo;</a></li>
            {% endif %}

            {%- for page in pagination.iter_pages() %}
                {% if page != pagination.page %}
                    <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=page) }}">{{ page }}</a></li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page }}</a>
                    </li>
                {% endif %}
            {%- endfor %}

            {% if pagination.has_next %}
                <li class="page-item"><a class="page-link" href="{{ url_for('product.index', page=pagination.next_num) }}">&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
{%- endmacro %}

restApi/modules/templates/product/_form.html
<div class="mb-3">
    {{ form.name.label }} 
    {{ form.name(class="form-control") }}
</div>

<div class="mb-3">
    {{ form.price.label }} 
    {{ form.price(class="form-control") }}
</div>

<div class="mb-3">
    {{ form.category_id.label }} 
    {{ form.category_id(class="form-control") }}
</div>

restApi/modules/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.create') }}" method="POST">
        {% include 'product/_form.html' %}
        <input class="btn btn-success" type="submit" value="Guardar">
    </form>
{% endblock %}

restApi/modules/templates/product/filter.html
<h3>{{ product['name'] }}</h3>
<p>{{ product['category'] }}</p>
<p>{{ product['price'] }}</p>

<p>Filtro default: {{ product['price'] | default('Sin precio', True) }}</p>
<p>Filtro safe: {{ "<h1>Hola, mundo</h1>" | safe }}</p>
<p>Filtro truncate: {{ "Esto es la descripción de un producto bastante bonito" | truncate(20) }}</p>
<p>Filtro count: {{ "Esto es la descripción de un producto bastante bonito" | count }}</p>
<p>Filtro float: {{ 70 | float }}</p>
<p>Filtro int: {{ "70.8" | int }}</p>
<p>Filtro round: {{ 3.1415926535 | round(3) }}</p>
<p>Filtro join: {{ ["iPhone", "iPad"] | join(", ") }}</p>
<p>Filtro length: {{ ["iPhone", "iPad"] | length }}</p>
<p>Filtro tojson: {{ {'offer': False, 'price': 50.5, 'k': 45} | tojson }}</p>
<p>Filtro global personalizado: {{ 50 | mydouble }}</p>
<p>Filtro local personalizado: {{ product | iva }}</p>

restApi/modules/templates/product/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}
    <a href="{{ url_for('product.create') }}" class="btn btn-primary mt-2 mb-2"><i class="fa fa-plus"></i> Crear</a>
    <br>
    <div class="list-product">
        {% for product in products.items %}
            <div class="p-4 mb-4 rounded-3 {{ loop.cycle('odd', 'even') }}">
                <h3>
                    <a href="{{ url_for('product.show', id=product['id']) }}">{{ product['name'] }}</a>
                </h3>
                <h5>{{ product['category'].name }}</h5>
                <a class="btn btn-warning btn-sm" href="{{ url_for('product.update', id=product['id']) }}"><i class="far fa-edit" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar"></i></a>
                <button type="button" data-bs-toggle="modal" data-bs-target="#deleteModal" data-bs-name="{{ product['name'] }}" data-bs-id="{{ product['id'] }}" class="btn btn-danger btn-sm"><i class="far fa-trash-alt" data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar"></i></button>
            </div>
        {% endfor %}
    </div>

    {{ m_pagination(products) }}

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Eliminar: <span></span></h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Estás seguro de querer borrar este registro?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <a href="#" id="deleteProduct" class="btn btn-danger">Eliminar</a>
            </div>
          </div>
        </div>
    </div>

    <script>
        window.onload = function() {
            var deleteModal = document.getElementById('deleteModal')
            deleteModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget
            var id = button.getAttribute('data-bs-id')
            var name = button.getAttribute('data-bs-name')
            var modalTitle = deleteModal.querySelector('.modal-title span')
            var modalBodyInput = deleteModal.querySelector('.modal-body input')
            modalTitle.textContent = name
            $("#deleteProduct").attr("href", "/delete-product/" + id)
            })
        }
    </script>    
{% endblock %}

restApi/modules/templates/product/show.html
{% extends 'layout/base.html' %}

{% block container %}
    <h3>{{ product['name'] }}</h3>

    <p>{{ product['category'] }}</p>
    <p>$ {{ product['price'] }}</p>

    {% if product['price'] >= 1000 %}
        <p>Precio regular</p>
    {% else %}
        <p>Precio oferta</p>
    {% endif %}
{% endblock %}

restApi/modules/templates/product/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.update', id=product.id) }}" method="POST">
        {% include 'product/_form.html' %}
        <input class="btn btn-success" type="submit" value="Actualizar">
    </form>
{% endblock %}