SQLAlchemy/modules/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('configuration.DevelopmentConfig')
db = SQLAlchemy(app)

from modules.product.views import product
app.register_blueprint(product)
db.create_all()

# SQLite
# sqlite:///database.db

# Postgres
# postgresql+psycopg2://user:password@ip:port/db_name

# MSSQL
# mssql+pyodbc://user:password@dsn_name

# Oracle
# oracle+cx_oracle://user:password@ip:port/db_name

@app.template_filter('mydouble')
def mydouble_filter(n:int):
    return n * 2

SQLAlchemy/modules/product/views.py
from flask import Blueprint, render_template, request, redirect, flash, get_flashed_messages
from flask.helpers import url_for
from modules import db
from sqlalchemy.sql.expression import not_, or_
from werkzeug.exceptions import abort
from werkzeug.utils import redirect
from modules.product.model.products import PRODUCTS
from modules.product.model.product import Product, ProductForm

product = Blueprint('product', __name__)

@product.route('/product')
@product.route('/product/<int:page>')
def index(page=1):
   return render_template('product/index.html', products = Product.query.paginate(page, 5))

@product.route('/product/<int:id>')
def show(id):
   product = Product.query.get_or_404(id)
   return render_template('product/show.html', product = product)

@product.route('/create-product', methods=['GET', 'POST'])
def create():
   form = ProductForm(meta={'csrf': False})

   if form.validate_on_submit():
      p = Product(request.form.get('name'), request.form.get('price'))
      db.session.add(p)
      db.session.commit()
      flash("Producto guardado exitosamente.")
      return redirect(url_for('product.create'))
   
   if form.errors:
      flash(form.errors, 'danger')

   return render_template('product/create.html', form=form)  

@product.route('/update-product/<int:id>', methods=['GET', 'POST'])
def update(id):
   form = ProductForm(meta={'csrf': False})
   product = Product.query.get_or_404(id)

   if request.method == 'GET':
      form.name.data = product.name
      form.price.data = product.price

   if form.validate_on_submit():
      product.name = form.name.data
      product.price = form.price.data
      db.session.add(product)
      db.session.commit()
      flash("Producto actualizado exitosamente.")
      return redirect(url_for('product.update', id=product.id))
   
   if form.errors:
      flash(form.errors, 'danger')


   return render_template('product/update.html', product=product, form=form)

@product.route('/test')
def test():
   # Consultas
   # p = Product.query.limit(2).all()
   # p = Product.query.first()
   # p = Product.query.order_by(Product.id.desc()).limit(3).all()
   # p = Product.query.get({ "id": 1})
   # p = Product.query.filter_by(name = "Producto 2").all()
   # p = Product.query.filter(Product.id > 1).all()
   # p = Product.query.filter_by(id = 2, name = "Producto 2").all()
   # p = Product.query.filter(Product.name.like('Producto%')).all()
   # p = Product.query.filter(not_(Product.id > 2)).all()
   # p = Product.query.filter(or_(Product.id > 2, Product.name == "Producto 2")).all()
   # print(p)

   # Crear
   # p = Product("Producto 5", 60.8)
   # db.session.add(p)
   # db.session.commit()

   # Actualizar
   # p = Product.query.filter_by(name = "Producto 1", id = 1).first()
   # p.name = "Teléfono 1"
   # db.session.add(p)
   # db.session.commit()

   # Eliminar
   # p = Product.query.filter_by(id = 5).first()
   # db.session.delete(p)
   # db.session.commit()
   return "CRUD"

@product.route('/delete-product/<int:id>')
def delete(id):
   product = Product.query.get_or_404(id)
   db.session.delete(product)
   db.session.commit()
   flash("Producto eliminado exitosamente.")
   return redirect(url_for('product.index'))

@product.route('/filter/<int:id>')
def filter(id):
   product = PRODUCTS.get(id)
   return render_template('product/filter.html', product = product)

@product.app_template_filter('iva')
def iva_filter(product):
   if product['price']:
      return product['price'] * 0.12
   else:
      return "Sin precio, no puede calcularse IVA."

SQLAlchemy/modules/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD</title>
</head>
<body>
    <header>Header de la app</header>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block container %}
        
    {% endblock %}

    <footer>Footer</footer>
</body>
</html>

SQLAlchemy/modules/templates/product/_form.html
{{ form.name.label }} {{ form.name }}
{{ form.price.label }} {{ form.price }}

SQLAlchemy/modules/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.create') }}" method="POST">
        {% include 'product/_form.html' %}
        <input type="submit" value="Guardar">
    </form>
{% endblock %}

SQLAlchemy/modules/templates/product/index.html
{% extends 'layout/base.html' %}

{% block container %}
    {% for product in products.items %}
        <div>
            <a href="{{ url_for('product.show', id=product['id']) }}">{{ product['name'] }}</a>
            <a href="{{ url_for('product.update', id=product['id']) }}">Editar</a>
            <a href="{{ url_for('product.delete', id=product['id']) }}">Eliminar</a>
        </div>
    {% endfor %}

    <div class=pagination>
        {%- for page in products.iter_pages() %}
            {% if page != products.page %}
                <a href="{{ url_for('product.index', page=page) }}">{{ page }}</a>
            {% else %}
                <strong>{{ page }}</strong>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

SQLAlchemy/modules/templates/product/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.update', id=product.id) }}" method="POST">
        {% include 'product/_form.html' %}
        <input type="submit" value="Actualizar">
    </form>
{% endblock %}